sudo: required
dist: trusty  
services:
  - docker
env:
  global:
    - DOCKER_NAME=joyreactor_server
    - DOCKER_ID=y2khub/joyreactor_server
before_install:
  - openssl aes-256-cbc -K $encrypted_ea8b612642af_key -iv $encrypted_ea8b612642af_iv -in deployment_key.txt.enc -out deployment_key.txt -d
  - chmod 600 deployment_key.txt
script:
  - docker build --rm -f Dockerfile -t $DOCKER_ID .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_ID
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o "StrictHostKeyChecking=no" -i deployment_key.txt $DEPLOY_AUTHORITY "docker pull $DOCKER_ID && docker rm -f $DOCKER_NAME || true && docker run --name $DOCKER_NAME -d -p 4567:4567 $DOCKER_ID"